### ISSUE TITLE
We need a source for restaurants list

### ISSUE THREAD

**Issue by yalefresne** [MyLittleParis/Random-Lunch#4]
For now it can be a file, and will be improve in futur.

**Comment by Erwin-Felix-MLP** [comment]
Discussed with @yalefresne, it can be : 
- A `Google Sheet` for the list of restaurant (format to define)
- File in a S3 (json for example).
- A SQlite database
- etc...

**Comment by yalefresne** [comment]
I just thought of something.  
It would be possible to allow slack users to suggest restaurants to add to the list.  
That doesn't answer the question of where we store the list, but it's an idea.

I continue to think that [google sheet](https://developers.google.com/sheets/api/quickstart/apps-script) is a good source for our needs.
